![image](https://user-images.githubusercontent.com/57321948/196933065-4b16c235-f3b9-4391-9cfe-4affcec87c35.png)

# Business Analytics

## 24 July 2021

## Numpy - II


# NumPy

- NumPy is a Python library.

- NumPy is used for working with arrays.

- NumPy is short for "Numerical Python".

In [ ]:
pip install numpy

## Basic Operations

In [1]:
import numpy as np

![image.png](attachment:image.png)

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
type(a)

numpy.ndarray

In [4]:
a = np.array([1,2,3], dtype = float)
print(a)

[1. 2. 3.]


In [5]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
type(b)

numpy.ndarray

In [7]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
#Get Dimensions of a numpy array
a.ndim

1

In [9]:
#Get Dimensions of a numpy array
b.ndim

2

In [10]:
c.ndim

2

In [11]:
d = np.array([[[[1,2,3], [4,5,6], [7,8,9]]]])
print(d)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [12]:
d.ndim

4

## Why Use NumPy?

- In Traditional Python Programming, we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

![image.png](attachment:image.png)

## Time taken for the loop

![image.png](attachment:image.png)

In [13]:
a

array([1., 2., 3.])

In [14]:
#Get a shape of a numpy array
a.shape

(3,)

In [15]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b.shape

(2, 3)

In [17]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
c.shape

(3, 3)

In [19]:
a

array([1., 2., 3.])

In [20]:
a

array([1., 2., 3.])

In [21]:
a.dtype

dtype('float64')

In [22]:
a_int = np.array([1.1,2.1,3.4])
print(a_int)

[1.1 2.1 3.4]


In [23]:
a_int.dtype

dtype('float64')

## Accessing/Changing specific elements, rows & columns etc.

In [24]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
a.ndim

2

In [26]:
#Get a specific element [r,c]
a[0,3]

4

In [27]:
a[1,0]

8

In [28]:
a[1,5]

13

In [29]:
#Get a specific row from a numpy array
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
#Get a specific column from a numpy array

a[:,0]

array([1, 8])

In [31]:
#Get a specific column from a numpy array
a[:,0]

array([1, 8])

In [32]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [33]:
a[0,3] = 40
print(a)

[[ 1  2  3 40  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [34]:
#Change the 5th column in 1st row to 50
a[0,4] = 50

In [35]:
a

array([[ 1,  2,  3, 40, 50,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

## Zeros/Ones method in NumPy

In [36]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.ones((3,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [39]:
np.full((3,3), 50, dtype='float64')

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]])

In [40]:
np.full((3,3), 50, dtype='int32')

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]], dtype=int32)

In [41]:
np.random.rand(4,4)

array([[0.39345773, 0.2375717 , 0.50435592, 0.99664518],
       [0.36470287, 0.1023309 , 0.48374213, 0.4850566 ],
       [0.83530678, 0.0140141 , 0.64043757, 0.85886675],
       [0.13743418, 0.62289688, 0.25254046, 0.73946041]])

In [42]:
np.random.randint(-4,4, size=(3,3))

array([[ 0,  1, -1],
       [-2, -4, -2],
       [-3, -4, -3]])

In [43]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Practice Questions

## Question #1

Extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?

In [44]:
2,3,4,5,6
20,30,40,50,60
12,12,12,12,12

(12, 12, 12, 12, 12)

In [45]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

In [46]:
a[ :3 , -5: ]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

## Question #2

Given a positive number 'n' greater than 2, create a NumPy array of size (nxn) with all zeros and ones such that the ones make a shape of "+"

Examples:

Input 1:

3

Output 1:

[[0 1 0]

 [1 1 1]

 [0 1 0]]

Input 2:

5

Output 1:

[[0 0 1 0 0]

 [0 0 1 0 0]

 [1 1 1 1 1]

 [0 0 1 0 0]

 [0 0 1 0 0]]

In [47]:
n=5

In [48]:
import numpy as np 

# Create an (nxn) array with all zeros
z = np.zeros((n,n), dtype='int')
print(z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [49]:
# Make the middle row and column all 1s

z[n//2,:] = 1
z[:,n//2] = 1

# Print the final value of z
print(z)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


#### Just to help you understand about n//2

In [50]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

In [51]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12, 12],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [52]:
a[5//2,:] = 1
print(a)

[[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]
 [ 1  1  1  1  1  1]
 [11 21 31 41 51 61]
 [13 24 34 44 54 64]]


In [53]:
a[:,n//2] = 1
print(a)

[[ 1  2  1  4  5  6]
 [10 20  1 40 50 60]
 [ 1  1  1  1  1  1]
 [11 21  1 41 51 61]
 [13 24  1 44 54 64]]


## Arithmetic Operations with NumPy - Maths + Stats

In [54]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [55]:
a = a+2

In [56]:
#DO it for -, /, *, //, ** - ALmost all the operations are satisfied

a**3

array([ 27,  64, 125, 216])

In [57]:
a

array([3, 4, 5, 6])

In [58]:
a.min()

3

In [59]:
a.max()

6

In [60]:
a.mean()

4.5

In [61]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
np.max(a)

8

In [63]:
a.max()

8

In [64]:
np.min(a)

1

In [65]:
np.mean(a)

4.5

In [66]:
np.sum(a)

36

In [67]:
np.max(a, axis=1)

array([4, 8])

In [68]:
np.max(a, axis=0)

array([5, 6, 7, 8])

In [69]:
np.min(a, axis=0)

array([1, 2, 3, 4])

In [70]:
np.min(a, axis=1)

array([1, 5])

In [71]:
np.sum(a, axis=1)

array([10, 26])

In [72]:
np.sum(a, axis=0)

array([ 6,  8, 10, 12])